namespace TOZ;

public enum CustomRoles
{
    // Default
    Crewmate = 0,

    // Impostors (Vanilla)
    Impostor,
    Phantom,
    Shapeshifter,

    // Vanilla Remakes
    ImpostorTOZ,
    PhantomTOZ,
    ShapeshifterTOZ,

    // Impostors

    Abyssbringer,
    Hacker, // Anonymous
    AntiAdminer,
    Sans, // Arrogance
    Augmenter,
    Bard,
    Blackmailer,
    Bomber,
    BountyHunter,
    OverKiller, // Butcher
    Camouflager,
    Capitalism,
    Cantankerous,
    Changeling,
    Chronomancer,
    Cleaner,
    Commander,
    EvilDiviner, // Consigliere
    Consort,
    Councillor,
    Crewpostor,
    CursedWolf,
    Deathpact,
    Devourer,
    Disperser,
    Duellist,
    Dazzler,
    Echo,
    Escapee,
    Eraser,
    EvilGuesser,
    EvilTracker,
    FireWorks,
    Freezer,
    Gambler,
    Gangster,
    Generator,
    Godfather,
    Greedier,
    Hangman,
    Hitman,
    Inhibitor,
    Kamikaze,
    Kidnapper,
    Minimalism, // Killing Machine
    BallLightning, // Lightning
    Librarian,
    Lurker,
    Mafioso,
    Mastermind,
    Mafia, // Nemesis
    SerialKiller, // Mercenary
    Miner,
    Morphling,
    Assassin, // Ninja
    Nuker,
    Nullifier,
    Overheat,
    Parasite,
    Penguin,
    Puppeteer,
    QuickShooter,
    Refugee,
    RiftMaker,
    Saboteur,
    Sapper,
    Scavenger,
    Silencer,
    Sniper,
    ImperiusCurse, // Soul Catcher
    Swapster,
    Swiftclaw,
    Swooper,
    Stealth,
    TimeThief,
    BoobyTrap, // Trapster
    Trickster,
    Twister,
    Underdog,
    Undertaker,
    Vampire,
    Ventriloquist,
    Vindicator,
    Visionary,
    Warlock,
    Wildling,
    Witch,
    YinYanger,
    Zombie,

    // Crewmates (Vanilla)
    Engineer,
    GuardianAngel,
    Noisemaker,
    Scientist,
    Tracker,

    // Vanilla Remakes
    CrewmateTOZ,
    EngineerTOZ,
    GuardianAngelTOZ,
    NoisemakerTOZ,
    ScientistTOZ,
    TrackerTOZ,

    // Crewmates

    CyberStar, // Celebrity
    Chameleon,
    LovingCrewmate,
    LovingImpostor,
    Detective,
    Doctor,
    Grenadier,
    Mayor,
    SabotageMaster, // Mechanic
    Medic,
    NiceGuesser,
    NiceSwapper,
    Sheriff,
    SuperStar,
    TaskManager,
    Veteran,

    // Neutrals

    Agitater,
    Amnesiac,
    Arsonist,
    Bandit,
    Bargainer,
    BloodKnight,
    Bubble,
    Chemist,
    Cherokious,
    Collector,
    Deathknight,
    Doppelganger,
    Doomsayer,
    Eclipse,
    Enderman,
    Evolver,
    Executioner,
    Totocalcio, // Follower
    Glitch,
    God,
    FFF, // Hater
    HeadHunter,
    HexMaster,
    Hookshot,
    Imitator,
    Impartial,
    Innocent,
    Jackal,
    Jester,
    Jinx,
    Juggernaut,
    Konan,
    Lawyer,
    Magician,
    Mario,
    Maverick,
    Medusa,
    Mycologist,
    Necromancer,
    Nonplus,
    Opportunist,
    Patroller,
    Pelican,
    Pestilence,
    Phantasm,
    Pickpocket,
    PlagueBearer,
    PlagueDoctor,
    Poisoner,
    Postman,
    Predator,
    Provocateur,
    Pursuer,
    Pyromaniac,
    Reckless,
    Revolutionist,
    Ritualist,
    Rogue,
    Romantic,
    RouleteGrandeur,
    RuthlessRomantic,
    Samurai,
    SchrodingersCat,
    NSerialKiller, // Serial Killer
    Shifter,
    Sidekick,
    Simon,
    SoulHunter,
    Spiritcaller,
    Sprayer,
    DarkHide, // Stalker
    Succubus,
    Sunnyboy,
    Terrorist,
    Tiger,
    Traitor,
    Tremor,
    Vengeance,
    VengefulRomantic,
    Virus,
    Vulture,
    Werewolf,
    WeaponMaster,
    Workaholic,

    // Solo Kombat
    KB_Normal,

    // FFA
    Killer,

    // Move And Stop
    Tasker,

    // Hot Potato
    Potato,

    // H&S
    Hider,
    Seeker,
    Fox,
    Troll,
    Jumper,
    Detector,
    Jet,
    Dasher,
    Locator,
    Venter,
    Agent,
    Taskinator,

    // Speedrun
    Runner,

    // GM
    GM,

    // ????
    Convict,


    // Sub-role after 500
    NotAssigned = 500,
    Antidote,
    AntiTP,
    Asthmatic,
    Autopsy,
    Avanger,
    Bait,
    Busy,
    Trapper, // Beartrap
    Bewilder,
    Bloodlust,
    Charmed,
    Circumvent,
    Cleansed,
    Clumsy,
    Contagious,
    Damocles,
    DeadlyQuota,
    Disco,
    Diseased,
    Dynamo,
    Unreportable, // Disregarded
    DoubleShot,
    Egoist,
    Energetic,
    EvilSpirit,
    Finder,
    Flashman,
    Fool,
    Giant,
    Glow,
    Gravestone,
    Guesser,
    Haste,
    Knighted,
    LastImpostor,
    Lazy,
    Lovers,
    Loyal,
    Lucky,
    Madmate,
    Magnet,
    Mare,
    Messenger,
    Mimic,
    Mischievous,
    Necroview,
    Nimble,
    Noisy,
    Oblivious,
    Onbound,
    Spurt,
    Sleep,
    Physicist,
    Rascal,
    Reach,
    Recruit,
    Rookie,
    DualPersonality, // Schizophrenic
    Seer,
    Sleuth,
    Sonar,
    Stained,
    Taskcounter,
    TicketsStealer, // Stealer
    Stressed,
    Swift,
    Sunglasses,
    Brakar, // Tiebreaker
    Torch,
    Truant,
    Undead,
    Unlucky,
    Watcher,
    Workhorse,
    Youtuber
}